name: Show Secret

on:
    push:
        branches: main

jobs:
    show-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Show the secret
              run: echo ${{secrets.GREETING}}
